const cupheadItems = [
  {
    id: 1,
    name: "Heart",
    image: "https://static.wikia.nocookie.net/cuphead/images/e/e8/Heart_Charm.png/revision/latest?cb=20180323191534",
    icon: "https://static.wikia.nocookie.net/cuphead/images/f/f0/HeartIcon.png/revision/latest?cb=20171021151555",
    description:
      "Adds an additional hit point but lightly weakens your attack power.",
    price: 3,
    availability: "Available immediately",
  },
  {
    id: 2,
    name: "Smoke Bomb",
    image: "https://static.wikia.nocookie.net/cuphead/images/f/f2/Smoke_Dash.png/revision/latest?cb=20180323191733",
    icon: "https://static.wikia.nocookie.net/cuphead/images/e/eb/Smoke_Bomb.png/revision/latest?cb=20171021151610",
    description:
      "You will not take damage during a dash. A great defense maneuver.",
    price: 3,
    availability: "Available immediately",
  },
  {
    id: 3,
    name: "P. Sugar",
    image: "https://static.wikia.nocookie.net/cuphead/images/c/cb/P_Sugar.png/revision/latest?cb=20180323192053",
    icon: "https://static.wikia.nocookie.net/cuphead/images/7/7e/PSugarIcon.png/revision/latest?cb=20171021151603",
    description:
      "The first parry move is automatic -- all you need to do is jump.",
    price: 3,
    availability: "Available after purchase of one of the initial 2 charms",
  },
  {
    id: 4,
    name: "Coffee",
    image: "https://static.wikia.nocookie.net/cuphead/images/e/e9/Coffee.png/revision/latest?cb=20180323192238",
    icon: "https://static.wikia.nocookie.net/cuphead/images/4/4a/CoffeeIcon.png/revision/latest?cb=20171021151548",
    description:
      "Super meter continuously fills -- in addition to what you earn.",
    price: 3,
    availability: "Requires purchase of 2 other charms",
  },
  {
    id: 5,
    name: "Twin Heart",
    image: "https://static.wikia.nocookie.net/cuphead/images/a/a5/Twin_Heart_Charm.png/revision/latest?cb=20180323192505",
    icon: "https://static.wikia.nocookie.net/cuphead/images/8/8a/TwinHeartIcon.png/revision/latest?cb=20171021151618",
    description:
      "Adds two additional hit points but weakens your attack power.",
    price: 5,
    availability: "Requires purchase of 3 other charms",
  },
  {
    id: 6,
    name: "Whetstone",
    image: "https://static.wikia.nocookie.net/cuphead/images/9/9f/Whetstone.png/revision/latest?cb=20180323191429",
    icon: "https://static.wikia.nocookie.net/cuphead/images/1/1f/WhetstoneIcon.png/revision/latest?cb=20171021151626",
    description: "Your first parry move doubles as a damaging axe attack.",
    price: 3,
    availability: "Requires purchase of 4 other charms or 1 DLC charm",
  },
  {
    id: 7,
    name: "Heart Ring",
    image: "https://static.wikia.nocookie.net/cuphead/images/6/63/HeartRing.png/revision/latest?cb=20220702235621",
    icon: "https://static.wikia.nocookie.net/cuphead/images/d/d2/HeartRingIcon.png/revision/latest?cb=20220702234730",
    description:
      "Restores one HP to the player for their first, third, and sixth parries.",
    price: 3,
    availability: "Available immediately in Inkwell Isle 4",
  },
  {
    id: 8,
    name: "Broken Relic",
    image: "https://static.wikia.nocookie.net/cuphead/images/7/76/BrokenRelic.png/revision/latest?cb=20220702235729",
    icon: "https://static.wikia.nocookie.net/cuphead/images/f/f9/BrokenRelicIcon.png/revision/latest?cb=20220702235125",
    description: "A simple bauble of unknown origin.",
    price: 1,
    availability: "Available immediately in Inkwell Isle 4",
  },
];

const cupheadWeapons = [
  {
    id: 1,
    weapon: "Spread",
    ex: "Eight Way",
    potion: "https://static.wikia.nocookie.net/cuphead/images/d/d2/Spread_potion.png/revision/latest?cb=20180322161317",
    icon: "https://static.wikia.nocookie.net/cuphead/images/2/28/SpreadIcon.png/revision/latest?cb=20171021090044",
    shot: "https://static.wikia.nocookie.net/cuphead/images/a/ab/Spread.png/revision/latest?cb=20180315193821",
    ex_shot: "https://static.wikia.nocookie.net/cuphead/images/f/ff/Eight_Way.png/revision/latest?cb=20180315194403",
    description:
      "Short range with great damage -- if you can keep close to your target.",
    price: 4,
    availability: "Available immediately",
  },
  {
    id: 2,
    weapon: "Chaser",
    ex: "Chaos Orbit",
    potion: "https://static.wikia.nocookie.net/cuphead/images/0/03/Chaser_potion.png/revision/latest?cb=20180322161532",
    icon: "https://static.wikia.nocookie.net/cuphead/images/5/5e/ChaserIcon.png/revision/latest?cb=20171021090220",
    shot: "https://static.wikia.nocookie.net/cuphead/images/2/22/Chaser.png/revision/latest?cb=20180315194523",
    ex_shot: "https://static.wikia.nocookie.net/cuphead/images/2/2c/Cuphead_chaser_ex.jpg/revision/latest?cb=20220324193031",
    description: "Long range with below-average damage. No aiming required.",
    price: 4,
    availability: "Available immediately",
  },
  {
    id: 3,
    weapon: "Lobber",
    ex: "Kablooey",
    potion: "https://static.wikia.nocookie.net/cuphead/images/2/20/Lobber_Potion.png/revision/latest?cb=20221212021224",
    icon: "https://static.wikia.nocookie.net/cuphead/images/4/49/LobberIcon.png/revision/latest?cb=20171021090213",
    shot: "https://static.wikia.nocookie.net/cuphead/images/c/cb/Lobber.png/revision/latest?cb=20180319182502",
    ex_shot: "https://static.wikia.nocookie.net/cuphead/images/4/41/Kablooey.png/revision/latest?cb=20180319182717",
    description: "Medium range and good damage with a slower rate of fire.",
    price: 4,
    availability:
      "Available after purchase of one of the initial 3 weapons or 2 purchases in the DLC shop",
  },
  {
    id: 4,
    weapon: "Charge",
    ex: "Radial Barrage",
    potion: "https://static.wikia.nocookie.net/cuphead/images/9/9a/Charge_potion.png/revision/latest?cb=20180322163516",
    icon: "https://static.wikia.nocookie.net/cuphead/images/9/9a/ChargeIcon.png/revision/latest?cb=20171021090227",
    shot: "https://static.wikia.nocookie.net/cuphead/images/d/db/Charge.png/revision/latest?cb=20180319182938",
    ex_shot: "https://static.wikia.nocookie.net/cuphead/images/f/f0/Radial_Barrage.png/revision/latest?cb=20180319190125",
    description:
      "Hold attack to increase damage. No rapid fire, so precision is key.",
    price: 4,
    availability: "Requires purchase of 2 other weapons or 1 DLC weapon",
  },
  {
    id: 5,
    weapon: "Roundabout",
    ex: "Jumbo Rebound",
    potion: "https://static.wikia.nocookie.net/cuphead/images/a/a2/Roundabout_potion.png/revision/latest?cb=20220802023024",
    icon: "https://static.wikia.nocookie.net/cuphead/images/2/23/RoundaboutIcon.png/revision/latest?cb=20171021090157",
    shot: "https://static.wikia.nocookie.net/cuphead/images/d/dc/Roundabout.png/revision/latest?cb=20180319182021",
    ex_shot: "https://static.wikia.nocookie.net/cuphead/images/7/79/Jumbo_Rebound.png/revision/latest?cb=20180319182243",
    description:
      "Great coverage with average damage. Aim backward for maximum range.",
    price: 4,
    availability: "Available immediately",
  },
  {
    id: 6,
    weapon: "Crackshot",
    ex: "P. Turret",
    potion: "https://static.wikia.nocookie.net/cuphead/images/0/0f/Crackshot_potion.png/revision/latest?cb=20220703120301",
    icon: "https://static.wikia.nocookie.net/cuphead/images/a/a1/CrackshotIcon.png/revision/latest?cb=20220702234155",
    shot: "https://static.wikia.nocookie.net/cuphead/images/b/b9/Crackshot.png/revision/latest?cb=20220703120607",
    ex_shot: "https://static.wikia.nocookie.net/cuphead/images/9/99/P._Turret.png/revision/latest?cb=20220703121354",
    description:
      "Straight shot with good damage. Breaks into weaker aimed projectiles.",
    price: 4,
    availability: "Available immediately in Inkwell Isle IV",
  },
  {
    id: 7,
    weapon: "Converge",
    ex: "Electro-Bolt",
    potion: "https://static.wikia.nocookie.net/cuphead/images/2/22/Converge_potion.png/revision/latest?cb=20220703000659",
    icon: "https://static.wikia.nocookie.net/cuphead/images/2/22/Converge_potion.png/revision/latest?cb=20220703000659",
    shot: "https://static.wikia.nocookie.net/cuphead/images/a/a8/Converge.png/revision/latest?cb=20220703121607",
    ex_shot: "https://static.wikia.nocookie.net/cuphead/images/c/c1/Electro-Bolt.png/revision/latest?cb=20220703123738",
    description:
      "Full screen piercing 3-way shot. Hold lock button to narrow spread.",
    price: 4,
    availability: "Available immediately in Inkwell Isle IV",
  },
  {
    id: 8,
    weapon: "Twist-Up",
    ex: "Cyclone Spiral",
    potion: "https://static.wikia.nocookie.net/cuphead/images/1/1b/Twist-Up_potion.png/revision/latest?cb=20220703000757",
    icon: "https://static.wikia.nocookie.net/cuphead/images/0/0a/TwistUpIcon.png/revision/latest?cb=20220702234128",
    shot: "https://static.wikia.nocookie.net/cuphead/images/2/2d/TwistUp.png/revision/latest?cb=20220703124205",
    ex_shot: "https://static.wikia.nocookie.net/cuphead/images/b/b0/Cyclone_Spiral.png/revision/latest?cb=20220703124633",
    description: "Rapid-fire shot with arced pathway and average damage.",
    price: 4,
    availability: "Available immediately in Inkwell Isle IV",
  },
];

export {cupheadItems, cupheadWeapons}